config/routes.rb
FirstApp::Application.routes.draw do

  root :to => 'dashboards#index'

  resources :business_lines
  resources :expenses

  # match '/dashboards' => 'dashboards#index'
end

app/models/business_line.rb
class BusinessLine < ActiveRecord::Base

  def monthly_gross_profit
    if ( margin.present? && monthly_revenue.present? ) 
      margin * monthly_revenue
    else
      0
    end
  end

  def value_of_position 
    if ( position_in_business.present? && valuation.present?)
      position_in_business * valuation
    else
      0
    end
  end

  def present_value_of_profit_stream(discount_rate)
    0
  end

end

app/models/expense.rb
class Expense < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/business_lines_controller.rb
class BusinessLinesController < ApplicationController
  # GET /business_lines
  # GET /business_lines.xml
  def index
    @business_lines = BusinessLine.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @business_lines }
    end
  end

  # GET /business_lines/1
  # GET /business_lines/1.xml
  def show
    @business_line = BusinessLine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @business_line }
    end
  end

  # GET /business_lines/new
  # GET /business_lines/new.xml
  def new
    @business_line = BusinessLine.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @business_line }
    end
  end

  # GET /business_lines/1/edit
  def edit
    @business_line = BusinessLine.find(params[:id])
  end

  # POST /business_lines
  # POST /business_lines.xml
  def create
    @business_line = BusinessLine.new(params[:business_line])

    respond_to do |format|
      if @business_line.save
        format.html { redirect_to(@business_line, :notice => 'Business line was successfully created.') }
        format.xml  { render :xml => @business_line, :status => :created, :location => @business_line }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @business_line.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /business_lines/1
  # PUT /business_lines/1.xml
  def update
    @business_line = BusinessLine.find(params[:id])

    respond_to do |format|
      if @business_line.update_attributes(params[:business_line])
        format.html { redirect_to(@business_line, :notice => 'Business line was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @business_line.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /business_lines/1
  # DELETE /business_lines/1.xml
  def destroy
    @business_line = BusinessLine.find(params[:id])
    @business_line.destroy

    respond_to do |format|
      format.html { redirect_to(business_lines_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index
    @business_lines = BusinessLine.all
    @expenses_to_show = Expense.all
  end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  # GET /expenses
  # GET /expenses.xml
  def index
    @expenses = Expense.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @expenses }
    end
  end

  # GET /expenses/1
  # GET /expenses/1.xml
  def show
    @expense = Expense.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @expense }
    end
  end

  # GET /expenses/new
  # GET /expenses/new.xml
  def new
    @expense = Expense.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @expense }
    end
  end

  # GET /expenses/1/edit
  def edit
    @expense = Expense.find(params[:id])
  end

  # POST /expenses
  # POST /expenses.xml
  def create
    @expense = Expense.new(params[:expense])

    respond_to do |format|
      if @expense.save
        format.html { redirect_to(@expense, :notice => 'Expense was successfully created.') }
        format.xml  { render :xml => @expense, :status => :created, :location => @expense }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @expense.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /expenses/1
  # PUT /expenses/1.xml
  def update
    @expense = Expense.find(params[:id])

    respond_to do |format|
      if @expense.update_attributes(params[:expense])
        format.html { redirect_to(@expense, :notice => 'Expense was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @expense.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.xml
  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to(expenses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_lines_helper.rb
module BusinessLinesHelper
end

app/views/business_lines/_form.html.erb
<%= form_for(@business_line) do |f| %>
  <% if @business_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business_line.errors.count, "error") %> prohibited this business_line from being saved:</h2>

      <ul>
      <% @business_line.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :monthly_revenue %><br />
    <%= f.text_field :monthly_revenue %>
  </div>
  <div class="field">
    <%= f.label :margin %><br />
    <%= f.text_field :margin %>
  </div>
  <div class="field">
    <%= f.label :valuation %><br />
    <%= f.text_field :valuation %>
  </div>
  <div class="field">
    <%= f.label :position_in_business %><br />
    <%= f.text_field :position_in_business %>
  </div>
  <div class="field">
    <%= f.label :full_time_workers %><br />
    <%= f.text_field :full_time_workers %>
  </div>
  <div class="field">
    <%= f.label :revenue_months %><br />
    <%= f.text_field :revenue_months %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/business_lines/edit.html.erb
<h1>Editing business_line</h1>

<%= render 'form' %>

<%= link_to 'Show', @business_line %> |
<%= link_to 'Back', business_lines_path %>

app/views/business_lines/index.html.erb
<h1>Listing business_lines</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Monthly revenue</th>
    <th>Margin</th>
    <th>Valuation</th>
    <th>Position in business</th>
    <th>Full time workers</th>
    <th>Monthly Gross Revenue</th>
    <th>Revenue months</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @business_lines.each do |business_line| %>
  <tr>
    <td><%= business_line.name %></td>
    <td><%= business_line.monthly_revenue %></td>
    <td><%= business_line.margin %></td>
    <td><%= business_line.valuation %></td>
    <td><%= business_line.position_in_business %></td>
    <td><%= business_line.full_time_workers %></td>
    <td><%= business_line.monthly_gross_profit %></td>
    <td><%= business_line.revenue_months %></td>
    <td><%= link_to 'Show', business_line %></td>
    <td><%= link_to 'Edit', edit_business_line_path(business_line) %></td>
    <td><%= link_to 'Destroy', business_line, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Business line', new_business_line_path %>

app/views/business_lines/new.html.erb
<h1>New business_line</h1>

<%= render 'form' %>

<%= link_to 'Back', business_lines_path %>

app/views/business_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @business_line.name %>
</p>

<p>
  <b>Monthly revenue:</b>
  <%= @business_line.monthly_revenue %>
</p>

<p>
  <b>Margin:</b>
  <%= @business_line.margin %>
</p>

<p>
  <b>Valuation:</b>
  <%= @business_line.valuation %>
</p>

<p>
  <b>Position in business:</b>
  <%= @business_line.position_in_business %>
</p>

<p>
  <b>Full time workers:</b>
  <%= @business_line.full_time_workers %>
</p>

<p>
  <b>Revenue months:</b>
  <%= @business_line.revenue_months %>
</p>


<%= link_to 'Edit', edit_business_line_path(@business_line) %> |
<%= link_to 'Back', business_lines_path %>

app/views/dashboards/index.html.erb
FOO HAT

<b> HI </b>

<div class='business-lines'>
Lines:
<ul>
<%- @business_lines.each do |line| %>
  <li>
  <%= line.name %>
  <%= line.monthly_gross_profit %>
  </li>
</ul>

<%- end %>
</div>

<div class='expenses'>
Expenses:
<%- @expenses_to_show.each do |exp| %>

<ul>
  <li>
    <%= exp.name %>
    <%= exp.amount %>
  </li>
</ul>
<% end %>

</div>

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Listing expenses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @expenses.each do |expense| %>
  <tr>
    <td><%= expense.name %></td>
    <td><%= expense.amount %></td>
    <td><%= link_to 'Show', expense %></td>
    <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
    <td><%= link_to 'Destroy', expense, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @expense.name %>
</p>

<p>
  <b>Amount:</b>
  <%= @expense.amount %>
</p>


<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>